# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 18:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracolien',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+\\d{9,15}$')], verbose_name='téléphone'),
        ),
    ]
