# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracole', '0002_auto_20160506_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracolien',
            name='address',
            field=models.TextField(blank=True, verbose_name='adresse complète'),
        ),
    ]
