# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracole', '0003_auto_20160518_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracolien',
            name='adhesion',
            field=models.DateField(blank=True, help_text='les dates doivent être au format JJ/MM/AAAA', null=True, verbose_name='Date d’adhésion'),
        ),
    ]
