language: python
dist: focal
sudo: required
python:
  - 3.9
services:
  - postgresql
  - docker
install:
  - pip install poetry psycopg2
  - poetry config virtualenvs.create false --local
  - poetry install --no-interaction --no-ansi
env:
  - SECRET_KEY='pipo' EMAIL_HOST_PASSWORD='pipo' POSTGRES_HOST='localhost' POSTGRES_PASSWORD='' RAVEN=False DSN=''
script:
  - python -Wa ./manage.py migrate
  - PYTHONWARNINGS=always ./manage.py test
  - flake8 .
  - yapf -dr .
  - mypy .
  - pydocstyle
  - safety check
  - pip install "git+https://github.com/${TRAVIS_REPO_SLUG}.git#egg=videgrenier"
after_success:
  - coveralls
