version: '3'

services:
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/videgrenier/sql:/var/lib/postgresql/data
  memcached:
    image: memcached:alpine
    restart: unless-stopped
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/videgrenier/srv:/srv
    env_file:
      - .env
    environment:
      - DB=postgres
      - MEMCACHED=True
      - RAVEN=False
    networks:
      - web
      - default
    labels:
      traefik.enable: "true"
      traefik.http.routers.videgrenier-app.rule: "Host(`videgrenier.${DOMAIN_NAME:-localhost}`)"

  nginx:
    image: nim65s/ndh
    restart: unless-stopped
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/videgrenier/srv:/srv:ro
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.http.routers.videgrenier-ngx.rule: "Host(`videgrenier.${DOMAIN_NAME:-localhost}) && PathPrefix(`/static`, `/media`)"

networks:
  web:
    external: true
