# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 20:31
from __future__ import unicode_literals

from django.db import migrations


def insert_sites(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.all().delete()
    Site.objects.create(domain='caracole.totheweb.fr', name='vide grenier caracole')


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_sites),
    ]
