# Generated by Django 2.0.3 on 2018-03-22 22:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepte', models.NullBooleanField(default=None, verbose_name='accepté')),
                ('birthdate', models.DateField(verbose_name='date de naissance')),
                ('birthplace', models.CharField(max_length=250, verbose_name='lieu de naissance')),
                ('id_num', models.CharField(max_length=100, verbose_name='numéro de la pièce d’identité')),
                ('id_date', models.DateField(verbose_name='date de délivrance de la pièce d’identité')),
                ('id_org', models.CharField(max_length=100, verbose_name='organisme délivrant la pièce d’identité')),
                ('plaque', models.CharField(max_length=20, verbose_name='numéro d’immatriculation du véhicule')),
                ('emplacements', models.IntegerField(default=1, verbose_name='nombre d’emplacements demandés')),
                ('nature', models.CharField(default='', max_length=250, verbose_name='nature des objets exposés')),
                ('phone_number',
                 models.CharField(
                     blank=True,
                     max_length=16,
                     validators=[django.core.validators.RegexValidator(regex='^\\+\\d{9,15}$')],
                     verbose_name='téléphone')),
                ('address', models.TextField(blank=True, verbose_name='adresse complète')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
