# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 15:43
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caracole', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepte', models.BooleanField(default=False, verbose_name='accepté')),
                ('caracolien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracole.Caracolien')),
            ],
        ),
    ]
