# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 19:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videgrenier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='caracolien',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='caracole.Caracolien'),
        ),
    ]
