# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 21:14
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videgrenier', '0002_auto_20160506_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='birthdate',
            field=models.DateField(default=datetime.date(1970, 1, 1), verbose_name='date de naissance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='birthplace',
            field=models.CharField(default='toulouse', max_length=250, verbose_name='lieu de naissance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_date',
            field=models.DateField(default=datetime.date(1970, 1, 1), verbose_name='date de délivrance de la pièce d’identité'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_num',
            field=models.CharField(default='0', max_length=100, verbose_name='numéro de la pièce d’identité'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_org',
            field=models.CharField(default='polisse', max_length=100, verbose_name='organisme délivrant la pièce d’identité'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='plaque',
            field=models.CharField(default='0', max_length=20, verbose_name='numéro d’immatriculation du véhicule'),
            preserve_default=False,
        ),
    ]
