# Generated by Django 3.1.7 on 2021-04-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videgrenier', '0002_phone_number_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='accepte',
            field=models.BooleanField(default=None, null=True, verbose_name='accepté'),
        ),
    ]
