# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videgrenier', '0003_auto_20160518_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='birthdate',
            field=models.DateField(help_text='les dates doivent être au format JJ/MM/AAAA', verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_date',
            field=models.DateField(help_text='les dates doivent être au format JJ/MM/AAAA', verbose_name='date de délivrance de la pièce d’identité'),
        ),
    ]
