# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videgrenier', '0004_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='emplacements',
            field=models.IntegerField(default=1, verbose_name='nombre d’emplacements demandés'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nature',
            field=models.CharField(default='', max_length=250, verbose_name='nature des objets exposés'),
        ),
    ]
