name: Tests
on: [push, pull_request]
env:
  SECRET_KEY: pipo
  EMAIL_HOST_PASSWORD: pipo
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: postgres
  RAVEN: False
  DSN: ""
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: setup
        run: |
          pip install psycopg2
          pipx install poetry
          poetry install --with dev --no-interaction --no-ansi

      - run: poetry run python -Wa ./manage.py migrate
      - run: PYTHONWARNINGS=always poetry run coverage run manage.py test
      - run: poetry run flake8 .
      - run: poetry run safety check
      - run: pip install "git+https://github.com/${GITHUB_REPOSITORY}.git#egg=videgrenier"

      - uses: codecov/codecov-action@v1
